seed: 42
exp_tag: EVA02-Endoscapes

data_path: data/endoscapes_2023/endoscapes
out_root: outputs/Eva02_Endoscapes

model_name: eva02_large_patch14_448.mim_m38m_ft_in22k_in1k
img_size: 448
num_classes: 3
label_type: ca

epochs: 16
batch_size: 16
num_workers: 8

lr: 1.188966836368374e-05
weight_decay: 0.0010414072113257376
no_amp: false

step_size: 2
gamma: 0.1

test_threshold: 0.5
use_pos_weight: false
